// Generated by scripts/i18n_build.mjs. Do not edit by hand.
//
// Part of the generated src/ui/i18n.resolved.generated/ directory: one dense
// locale slice per file (each `: EnTranslations` = typeof en, so tsc red-fails a
// missing or renamed key), a back-compat barrel (index.ts) that re-exports every
// slice and assembles the runtime `translations` map, per-locale lazy loaders
// (loaders.ts), and the pending set (pending.ts). Regenerate with
// `npm run i18n:build` (also wired into `npm run build` and `pretest`).
// Reproducibility is checked by tests/i18n_resolved_equivalence.test.ts.

export const pending: Record<string, readonly string[]> = {
  "es": [
    "delveUi.board.companion.boon",
    "delveUi.board.companion.maxRank",
    "delveUi.board.companion.upgrade",
    "delveUi.board.companion.upgradeAria",
    "delveUi.board.tabDelve",
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "delveUi.shop.buyAria",
    "delveUi.shop.empty",
    "delveUi.shop.price",
    "delveUi.shop.reqClears",
    "delveUi.shop.reqHeroic",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm",
    "sim.delve.levelRequiredTier",
    "sim.delve.shopItemLocked",
    "sim.delve.shopMarksRequired",
    "sim.delve.shopSealPremiumOnly"
  ],
  "es_ES": [
    "delveUi.board.companion.boon",
    "delveUi.board.companion.maxRank",
    "delveUi.board.companion.upgrade",
    "delveUi.board.companion.upgradeAria",
    "delveUi.board.tabDelve",
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "delveUi.shop.buyAria",
    "delveUi.shop.empty",
    "delveUi.shop.price",
    "delveUi.shop.reqClears",
    "delveUi.shop.reqHeroic",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm",
    "sim.delve.levelRequiredTier",
    "sim.delve.shopItemLocked",
    "sim.delve.shopMarksRequired",
    "sim.delve.shopSealPremiumOnly"
  ],
  "fr_FR": [
    "delveUi.board.companion.boon",
    "delveUi.board.companion.maxRank",
    "delveUi.board.companion.upgrade",
    "delveUi.board.companion.upgradeAria",
    "delveUi.board.tabDelve",
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "delveUi.shop.buyAria",
    "delveUi.shop.empty",
    "delveUi.shop.price",
    "delveUi.shop.reqClears",
    "delveUi.shop.reqHeroic",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm",
    "sim.delve.levelRequiredTier",
    "sim.delve.shopItemLocked",
    "sim.delve.shopMarksRequired",
    "sim.delve.shopSealPremiumOnly"
  ],
  "fr_CA": [
    "delveUi.board.companion.boon",
    "delveUi.board.companion.maxRank",
    "delveUi.board.companion.upgrade",
    "delveUi.board.companion.upgradeAria",
    "delveUi.board.tabDelve",
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "delveUi.shop.buyAria",
    "delveUi.shop.empty",
    "delveUi.shop.price",
    "delveUi.shop.reqClears",
    "delveUi.shop.reqHeroic",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm",
    "sim.delve.levelRequiredTier",
    "sim.delve.shopItemLocked",
    "sim.delve.shopMarksRequired",
    "sim.delve.shopSealPremiumOnly"
  ],
  "en_CA": [],
  "it_IT": [
    "delveUi.board.companion.boon",
    "delveUi.board.companion.maxRank",
    "delveUi.board.companion.upgrade",
    "delveUi.board.companion.upgradeAria",
    "delveUi.board.tabDelve",
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "delveUi.shop.buyAria",
    "delveUi.shop.empty",
    "delveUi.shop.price",
    "delveUi.shop.reqClears",
    "delveUi.shop.reqHeroic",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm",
    "sim.delve.levelRequiredTier",
    "sim.delve.shopItemLocked",
    "sim.delve.shopMarksRequired",
    "sim.delve.shopSealPremiumOnly"
  ],
  "de_DE": [
    "delveUi.board.companion.boon",
    "delveUi.board.companion.maxRank",
    "delveUi.board.companion.upgrade",
    "delveUi.board.companion.upgradeAria",
    "delveUi.board.tabDelve",
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "delveUi.shop.buyAria",
    "delveUi.shop.empty",
    "delveUi.shop.price",
    "delveUi.shop.reqClears",
    "delveUi.shop.reqHeroic",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm",
    "sim.delve.levelRequiredTier",
    "sim.delve.shopItemLocked",
    "sim.delve.shopMarksRequired",
    "sim.delve.shopSealPremiumOnly"
  ],
  "zh_CN": [
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm"
  ],
  "zh_TW": [
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm"
  ],
  "ko_KR": [
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm"
  ],
  "ja_JP": [
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm"
  ],
  "pt_BR": [
    "delveUi.board.companion.boon",
    "delveUi.board.companion.maxRank",
    "delveUi.board.companion.upgrade",
    "delveUi.board.companion.upgradeAria",
    "delveUi.board.tabDelve",
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "delveUi.shop.buyAria",
    "delveUi.shop.empty",
    "delveUi.shop.price",
    "delveUi.shop.reqClears",
    "delveUi.shop.reqHeroic",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm",
    "sim.delve.levelRequiredTier",
    "sim.delve.shopItemLocked",
    "sim.delve.shopMarksRequired",
    "sim.delve.shopSealPremiumOnly"
  ],
  "ru_RU": [
    "delveUi.board.tabShop",
    "delveUi.shop.buy",
    "hudChrome.perf.groups.input",
    "hudChrome.perf.labels.apm"
  ]
};
